### ISSUE TITLE
サイドメニュー

### ISSUE THREAD

**Issue by s1f10240053** [caru-ini/class-7-team-2-team-project#2]

**Comment by caru-ini** [comment]
みんなで1つのファイルを作成すると、コンフリクト(衝突)が起きて少し操作が難しいので、それぞれファイルを作って書いてください。場所は`menu/main/メニュー名.html` (メニュー名は各自書き換え)で作成してください。テンプレートは後で作成しますのでお待ちください！

**Comment by caru-ini** [comment]
次回までに紹介するメニューを決めておいてください！

**Comment by caru-ini** [comment]
おつかれさまです！
